# Setup
title: "Paradigm Shift" # the name of your site, e.g. ACME Corp.
url: "http://paradigm-shift-jekyll.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  syntax_highlighter: rouge

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
